"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 05:03:37.625924
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('admin_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_logs'))
    )
    op.create_index('ix_admin_audit_logs_created', 'admin_audit_logs', ['created_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stars_amount', sa.BigInteger(), nullable=False),
    sa.Column('price_uzs', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_uzs > 0', name=op.f('ck_products_price_positive')),
    sa.CheckConstraint('stars_amount > 0', name=op.f('ck_products_stars_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('stars_amount', name=op.f('uq_products_stars_amount'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_table('deposits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('reject_reason', sa.String(length=300), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_deposits_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_deposits_amount_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_deposits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deposits')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_deposits_user_idempotency')
    )
    op.create_index('ix_deposits_status_created', 'deposits', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_deposits_user_id'), 'deposits', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('stars_amount', sa.BigInteger(), nullable=False),
    sa.Column('price_uzs', sa.BigInteger(), nullable=False),
    sa.Column('recipient_username', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending_admin', nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('admin_note', sa.String(length=300), nullable=True),
    sa.Column('processed_by', sa.BigInteger(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending_admin', 'approved', 'processing', 'completed', 'rejected', 'refunded', 'failed')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('price_uzs > 0', name=op.f('ck_orders_price_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_orders_user_idempotency')
    )
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_wallets_balance_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('user_id', name=op.f('uq_wallets_user_id'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('deposit_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('actor_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('deposit', 'order_debit', 'order_refund')", name=op.f('ck_transactions_type_valid')),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_transactions_amount_non_zero')),
    sa.CheckConstraint('balance_after >= 0', name=op.f('ck_transactions_balance_after_non_negative')),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], name=op.f('fk_transactions_deposit_id_deposits')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_transactions_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_transactions_wallet_id_wallets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('idempotency_key', name='uq_transactions_idempotency_key')
    )
    op.create_index('ix_transactions_user_created', 'transactions', ['user_id', 'created_at'], unique=False)
    op.create_index('uq_transactions_deposit_type', 'transactions', ['deposit_id', 'type'], unique=True, postgresql_where=sa.text('deposit_id IS NOT NULL'))
    op.create_index('uq_transactions_order_type', 'transactions', ['order_id', 'type'], unique=True, postgresql_where=sa.text('order_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_transactions_order_type', table_name='transactions', postgresql_where=sa.text('order_id IS NOT NULL'))
    op.drop_index('uq_transactions_deposit_type', table_name='transactions', postgresql_where=sa.text('deposit_id IS NOT NULL'))
    op.drop_index('ix_transactions_user_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_deposits_user_id'), table_name='deposits')
    op.drop_index('ix_deposits_status_created', table_name='deposits')
    op.drop_table('deposits')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('products')
    op.drop_index('ix_admin_audit_logs_created', table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
